name: predict_auto
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.23.0
  - scikit-learn>=1.2.0
  - xgboost>=1.7.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - shap>=0.41.0
  - scipy>=1.10.0
  - streamlit
  - plotly
  - statsmodels
  - google-generativeai
  - tqdm
  - pip
  - pip:
    - colorama
    - yfinance
    - python-dotenv
    - joblib
